### ISSUE TITLE
请问这种是什么情况

### ISSUE THREAD

**Issue by jkjoy** [KeKe12030/DiscuzToFlarum#1]
正在转换帖子..............
```
java.sql.SQLSyntaxErrorException: Unknown column 'position' in 'where clause'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1208)
        at cn.mcplugin.dz2flarum.DiscuzSQLUtil.getMessageByTid(DiscuzSQLUtil.java:443)
        at cn.mcplugin.dz2flarum.FlarumSQLUtil.transformationThread(FlarumSQLUtil.java:234)
        at cn.mcplugin.dz2flarum.Main.main(Main.java:37)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.close()" because "rs" is null
        at cn.mcplugin.dz2flarum.DiscuzSQLUtil.getMessageByTid(DiscuzSQLUtil.java:453)
        at cn.mcplugin.dz2flarum.FlarumSQLUtil.transformationThread(FlarumSQLUtil.java:234)
        at cn.mcplugin.dz2flarum.Main.main(Main.java:37)
```

**Comment by jkjoy** [comment]
```
java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`flarum`.`flarum_posts`, CONSTRAINT `flarum_posts_discussion_id_foreign` FOREIGN KEY (`discussion_id`) REFERENCES `flarum_discussions` (`id`) ON DELETE CASCADE)
```
